### ISSUE TITLE
Graphics bug

### ISSUE THREAD

**Issue by Suddow** [zmilla93/SlimTrade#5] opened 2020-03-14 00:39 UTC
When mousing over stuff many elements will frequently disappear

https://i.imgur.com/AsemCmI.png

Or bug out

https://i.imgur.com/zWkAyyL.png

**Comment by zmilla93** [comment] 2020-03-14 07:40
Well that is pretty horrible. Can you give me some rough PC specs? Operating system and graphics card specifically would be very useful.

**Comment by Suddow** [comment] 2020-03-14 16:55
Sure, I have windows 10 1903, ryzen 7 3700x, 16gb ram 3200, nvidia 1080ti on current driver.

Features in the addon?  All's default.  For POE, 1440p windowed fullscreen, vsync off, AA off, lighting shadows default, shadow quality low, sun shadow quality low, number of lights low, post process enabled, water detail low, texture quality high, filtering trilinear, dynamic res disabled and multithreading enabled.

Here's more of it in action:   https://gfycat.com/annualidealisticiberianemeraldlizard

**Comment by zmilla93** [comment] 2020-03-14 20:28
Does this happen all the time, or just sometimes?

I've noticed some bugs within the multi threading, so I'm really hoping that is the root cause. I should have an update out within the next day or two to fix some of those issues.

**Comment by Suddow** [comment] 2020-03-14 21:57
It seems to be very consistent.  There was one time it wasn't happening early on (when I didn't know about the issue), but it hasn't happened again so I don't really know why it worked once.

**Comment by zmilla93** [comment] 2020-03-15 06:36
Roughly how long does it take from the time you launch the program until it bugs out? Also do you use any features in that time, like trade messages or resizing windows?

[Here is a pre-release containing the multithread fixes.](https://github.com/zmilla93/SlimTrade/releases/tag/PRE-v0.0.0)

Let me know if that version fixes these issues or not, else it is back to the drawing board.

**Comment by Suddow** [comment] 2020-03-15 22:04
It happens immediately.  I've tried disabling gsync just in case, and it didn't help.  The pre-release version didn't fix it either.  It's still usable though, I just gotta mouseover where the buttons are to see them.  By the way, on that note I do have a couple suggestions:

it'd be nice if we could edit or remove any of the preset macros.
And the leave group button should also remove the popup for that entry (or have that be an option).

**Comment by zmilla93** [comment] 2020-03-17 02:32
Can you clarify if you are having issues with all the windows, or just some of them? If it is just some, please list which ones do and do not have issues (options, history, chat scanner, popups).

The monitor thing is very interesting. I have some more ideas, just want to make sure I know which windows are having the issues first.

A few people have asked about the macro buttons, so I've opened a new issue for that outlining my plans.

**Comment by Suddow** [comment] 2020-03-18 14:49
It appears to be every single window with the only exception being the top left dropdown (with history, scanner, options and quit buttons).  When a window open it usually looks fine, until I mouse over a button, and then it starts messing up like the gif I pasted.  Though, the exception to that is the chat alert when someone whispers me, it seems to show up already messed up.  I'll try to clip an example of that later.

Oddly in this new clip you can see it doesn't happen on some windows right away, seems to be the case when the window isn't immediately the focus or something like that?  But as soon as I click on it that happens.  Also it drags really slowly on my main screen, super delayed like you see when I accidentally drag one window down.

https://gfycat.com/SolidJoyfulHen

I wonder why I am the only one having this problem lol.  I figure its something on my end but I can't narrow it down yet.

**Comment by zmilla93** [comment] 2020-03-18 21:41
It could be related to either the UI layout system or the painting functions. I'll be going through and improving the quality of some older parts of code, but nothing that I can really quickly test. I imagine the bug is fairly subtle, but you have the perfect machine for it to appear frequently.

The slow moving window looks like a bug with the prerelease as I had that as well. Make sure to get the latest version, which is currently 0.2.4.

**Comment by Suddow** [comment] 2020-03-18 22:31
Yeah I updated after I recorded that, didn't change the bug though.  Here's an example of the popup, it showed up like this without any mouseover

https://i.imgur.com/yZyoJuA.png

**Comment by Suddow** [comment] 2020-03-21 02:10
I don't know why, but the bug stopped...  I wish I could say something specific did it, but honestly nothing changed.

**Comment by zmilla93** [comment] 2020-03-21 23:35
Interesting, I just got a second report on this from reddit.

2nd Report Specs :
Windows 10, GTX 1060 6GB, Ryzen 5 3600, 32GB DDR4 Ram

My own specs (without issue):
Windows 10, GTX 970, Intel i7, 16GB RAM

The obvious thing that stands out is the ryzen processor. I'm hoping when I do a cleanup of the old code soon I can eliminate the root cause of this.

**Comment by zmilla93** [comment] 2020-04-04 05:55
Version 0.2.5 contains a handful of small changes that I'm hoping will fully resolve these issues. If you have any more cases of graphical glitches on this new version, please report them. If there are no reports for a good period of time, I'll hopefully be able to close this issue.

**Comment by zmilla93** [comment] 2020-06-17 20:36
Closing due to no additional reports. If anyone else experiences this issue, feel free to open a new issues thread.

**Comment by schn4ppi** [comment] 2020-06-19 15:14
I have the same issue, when I open SlimTrade settings i cannot configure due to eversything overlapping :(

**Comment by zmilla93** [comment] 2020-06-19 15:50
I did some troubleshooting last night with someone who was having this issue, and for whatever reason disabling the menubar seemed to resolve it. All of the menubar options can still be can still be accessed via the SlimTrade icon in the system tray, or can be assigned hotkeys for easier access.

Options > General > Toggle Features > Uncheck Menubar Button. It is near the bottom of the general section, so you'll have to scroll down.

If you can't get to the toggle features due to the bug, you can manually edit the save file. Type `%localappdata%` into the file explorer to open the local app data folder, open the SlimTrade folder, then open settings.json with a text editor. Change the line `"enableMenubar":true` from true to false, then save and relaunch. The full path for this folder is `C:\Users\USERNAME\AppData\Local\SlimTrade`.

**Comment by schn4ppi** [comment] 2020-06-19 18:48
worked for me, thank you

**Comment by olavr-dev** [comment] 2021-01-16 08:46
Disabling the menubar worked for me as well. Thanks a lot, it was driving me crazy.

**Comment by benbaginski** [comment] 2021-01-22 03:09
I'd like to add that disabling the Menubar Button does stop the issue from occuring 100% of the time to only every now and then.

Not sure what conditions cause it to occur now, but I still sometimes get the popup graphically glitched like in the examples posted above.

**Comment by sgtdeagle** [comment] 2021-02-06 11:48
this only happens when die Overlay or the Options Menü is above the Game window. on second Screen the issue istant disapeard without restarting or reopening the Settings window.

**Comment by luizpasqualetto** [comment] 2021-02-28 12:46
Also suffering from this issue, my specs are : Windows 10, GTX 1660 ti, i7-9750H, 16Gb.
moving the windows to a second monitor solves the issue completely, it seems to have to do with how it overlays over path of exile.
I've attempted to switch windowed modes to fix it, disabled other overlay applications completely and a few other things like reinstalling, restarting etc. but nothing has fixed the issue

**Comment by djodars89** [comment] 2021-03-14 19:49
Recently changed computer and stumbled upon this issue. I can confirm that changing "enableMenubar" from true to false fixed the issue.

Went from Core i7 4770k (didn't have the issue) to Ryzen 7 5800x (had the issue before settings change).

**Comment by zmilla93** [comment] 2021-10-17 01:04
v0.3.4 contains some fairly significant multithreading fixes related to the UI. While I'm certain these will resolve the issue, it would be great if someone who has this issue could test it out.

**Comment by V4ldaran** [comment] 2021-10-30 18:04
I got that problem and unfortunately it didnt fixed it, i still need to disable the Menubar Button to have slimtrade working properly.

**Comment by dans-carimus** [comment] 2022-02-23 04:35
I was experiencing this glitch too running Java via Amazon Corretto 17. Disabling the menubar did seem to work around it.

**Comment by sfedu-admin** [comment] 2023-08-18 09:18
Win11. Java 8.381. Ryzen 7 5700x. UI completely unusable
![Screenshot 2023-08-18 121659](https://github.com/zmilla93/SlimTrade/assets/93139033/a0f1ca9d-ed3c-49d9-805a-764f25aee33e)

**Comment by zmilla93** [comment] 2024-03-25 22:20
I believe this issue is finally resolved in v0.4.0. Since I can't reproduce it, I'll need others to verify for me.

Will close this issue if there is no more activity for a while.

**Comment by djodars89** [comment] 2024-03-25 22:24
Looks good to me!

**Comment by zmilla93** [comment] 2024-04-06 21:47
No reports for a week, this should be fixed finally. 

The issue was actually embarrassingly simple to solve. The `pack` function needed to be called on all windows, which internally revalidates all layouts. Calling `revalidate` would likely also work. Still unsure why the bug was so inconsistent.

It wasn't until I took a break from this project and worked on something else that I was able to reproduce it in that other project and find a fix. Very glad to finally have this one addressed, sorry for the wait!

**Closed by zmilla93** 2024-04-06 21:47 UTC
Labels: bug, requires more info, temp fix
