### ISSUE TITLE
Overlay don't stays on top of PoE

### ISSUE THREAD

**Issue by thepoolhjk** [zmilla93/SlimTrade#27] opened 2020-05-11 02:08 UTC
hi, i can't see the little slim trade icon in the top-left corner. if i hit the windows key and open the options in the taskbar and i click on the opend options screen, the icon in the top-left corner appears. if i close the slim trade options menu, the icon in the top-left disappears.

if the icon is there(when i have opened the slim trade options and clicked on the options window), the program works. if the icon is not there, the program doesn't work.

if have added screenshots

![01](https://user-images.githubusercontent.com/51041459/81517987-e6ef8880-933c-11ea-85b5-ca248792b8e0.PNG)
![02e](https://user-images.githubusercontent.com/51041459/81517994-ebb43c80-933c-11ea-9723-037dc3b9cda6.png)
![03e](https://user-images.githubusercontent.com/51041459/81518000-efe05a00-933c-11ea-9035-12e72ebacdfe.png)
![04e](https://user-images.githubusercontent.com/51041459/81518006-f373e100-933c-11ea-84dc-ed2c20febfbb.png)
![05e](https://user-images.githubusercontent.com/51041459/81518010-f79ffe80-933c-11ea-917a-eaaa5510988a.png)

**Comment by zmilla93** [comment] 2020-05-11 02:23
Thanks for the detailed report! I'm guessing your operating system isn't set to English?

Regardless, what is the title of the POE window? This can be seen either by setting POE to windowed mode, or when hovering over the POE icon in the taskbar. [Example using task bar.](https://imgur.com/a/6xf3m1c)

Currently the way alt tabbing works is by reading the window title of whatever you click, and if the window has the title of "Path of Exile" or one of the SlimTrade windows, the overlay is forced to the top. If this check fails, the overlay is hidden since the assumption is that you are tabbed out. It sounds like this check is failing when you click the game.

**Comment by thepoolhjk** [comment] 2020-05-11 02:47
tx for the quick answer. windows language is german. ok if i switch to windowed the tool works. but i need fullscreen windowed :)

screen added with title "Path of Exile". is the same title in windowed fullscreen.

![11-05-20 at 04 45](https://user-images.githubusercontent.com/51041459/81519736-84998680-9342-11ea-9e76-a5736b945cf5.PNG)

**Comment by zmilla93** [comment] 2020-05-11 03:08
Rather unexpected that it works in windowed but not windowed full screen. I've created a version that will print some debugging info when running the program from the command line. This will print the title of all the windows you click as the program sees it, as well as some info about the result of the check. It would be awesome if you could tell me the result of this in both windowed and windowed full screen.

[Debug version of SlimTrade.](https://github.com/zmilla93/SlimTrade/releases/tag/PRE-v0.0.2)

[How to run from the command line.](https://github.com/zmilla93/SlimTrade/wiki/Running-from-Command-Line)

**Comment by thepoolhjk** [comment] 2020-05-11 06:47
i don't know why but now it works in windowed fullscreen after i had windowed. i changed nothing and had 100% windowed fullscreen before because of other tools. if the problem will appear again i use your debug version and report to you. but for now im happy :)

one thing i noticed. i have a tool called PoE overlay which gives me info about prizings. if i click shift+f for info on an item and i sendet an outgoing trade with slim trade before, it will trigger slim trade to send that trade question again to the same player. and again and again every time i send the question with shift+f to the other tool. have to use hotkey instead of automatic because of this.

but overall its a nice tool ;)

**Comment by zmilla93** [comment] 2020-05-12 00:16
Odd, but glad that it is at least working now. I'll leave this issue open for a bit in case it reoccurs.

My initial guess on the latter issue is that POE Overlay uses the clipboard temporarily for price checking, but then resets the contents of the clipboard back to what it was before. If that is the case, resetting the clipboard back to a trade message would trigger SlimTrade's auto quick paste function. I'll have to take a look at that program and see if that theory is correct.

**Comment by zmilla93** [comment] 2020-06-17 20:40
I did some brief testing with POE Overlay and was unable to reproduce the shift + F bug. If it is still occurring, feel free to open a new issues thread with the steps that cause the issue to occur. Also be sure your using the latest version of both programs.

Closing this thread since the main issue seemed to resolve itself.

**Closed by zmilla93** 2020-06-17 20:40 UTC
Labels: bug
