### ISSUE TITLE
Character name not saved correctly

### ISSUE THREAD

**Issue by tschmidt1** [zmilla93/SlimTrade#38] opened 2021-05-01 13:55 UTC
My character name is "TLSㆍUltㆍWander". When I paste this into the corresponding field, everything is working fine. However, after restarting SlimTrade, the name is replaced by "TLS?Ult?Wander", and things like kicking myself from the group after a trade doesn't work anymore.

**Comment by zmilla93** [comment] 2021-05-11 01:19
Looks to be some sort of encoding issue. While I'm not exactly sure why this is happening, I'm able to reproduce it myself so I'll be able to look for a solution.

**Comment by zmilla93** [comment] 2021-10-17 01:10
Sorry for the long wait, but this issue is now fully resolved in v0.3.4.

Characters not saving correctly was due to the save/load system not forcing UTF-8. My test environment already forced UTF-8, so I didn't noticed this was an issue for a while.

Characters appearing as boxes was due to the default Java font not supporting certain languages. I've added two new international fonts and made UI elements switch their font when they detect characters in these languages.

**Closed by zmilla93** 2021-10-17 01:10 UTC
Labels: bug
